### ISSUE TITLE
Injection fails with ALT_L mapped to SHIFT_L (beta)

### ISSUE THREAD

**Issue by jonasBoss** [sezanzeb/input-remapper#441]
Ok, so not sure if I should open a new issue or if this is related --

After adding the joystick on analog, everything was working fine. All bindings were good, joystick control was good. I decided to remap one of the keys originally pointing to ALT_L to SHIFT_L. I made no other changes to the config.

I then tried to restart injection and input-mapper reported "Staring injection" bottom left, but the "stop injection" never lit up. The injections weren't happening. I swapped the key binding back, but same problem. Restarted input-mapper, same problem. I did a system halt and brought everything up from scratch, same problem. I rebuilt the beta and did an apt remove and re-installed. Same problem

If I wait long enough, bottom left eventually goes to "injection failed" state. 

I'm pretty confused as everything was working and the change I made was minor - and the fact this bad state persisted through a re-install and a system halt is even more impressive. Not sure what happened.

Only other thing I'm thinking of doing is deleting the whole key binding list and rebuilding from scratch. If that works I'll report back

_Originally posted by @tfulmer1 in https://github.com/sezanzeb/input-remapper/issues/437#issuecomment-1193228081_

**Comment by jonasBoss** [comment]
Can you pleas post logs from both the service and the gui?

 - close the gui and stop the service with `systemctl stop input-remapper`
 - start the service with `sudo input-remapper-service -d`
 - start the gui with `input-remapper-gtk -d`
 - make sure the error occurs and post the logs

**Comment by tfulmer1** [comment]
[input-remapper-gui.log](https://github.com/sezanzeb/input-remapper/files/9176295/input-remapper-gui.log)
[input-remapper-log.txt](https://github.com/sezanzeb/input-remapper/files/9176296/input-remapper-log.txt)

Ok, so I started the daemon and the gui with a &> to redirect both to log files.

I started with a clean config, renamed it test and just mapped the joystick forward/back/left/right to analog gamepad Y and X values. Then started injection and ended up in the failed state. Hopefully those attachments work

**Comment by jonasBoss** [comment]
that helps, I am able to reproduce the bug.

You forgot to enable the "use as analog" switch for the joystick-y mapping.

I can see two bugs:
 - The Gui does not show a warning for this issue.
 - The service should not crash, and just log an error and ignore the mapping.

**Comment by tfulmer1** [comment]
Ultimately the above seemed to work, but may have another silent bug for you.

None of them had "Use as analog" selected. I recorded the buttons as Joystick-Y Up, Joystick-Y Down, Joystick-X Left, Joystick-X right and had set each one to analog x or y axis. Which I believe worked the first time, but not sure why.

Based on your feedback I went to set Y up and down to analog. I set Y up Analog, then tried to set Y down analog and the application crashed. I restarted and set Y Up analog, Y down analog (crash). I logged in again and set Y up, analog, X left Analog. No crash. Tries to set Y down analog (crash).

So I deleted mappings and started from scratch. I created Y up, set to analog and noticed it renamed Y-up to just Joystick-Y. So I then recorded Joystick-X Left and set it to analog and it set to just Joystic-X. I started injection and can now move the character with the joystick.

So your fix was correct, but you also seem to have an unhandled exception if setting the same axis twice. If that description is not enough to reproduce for you, I'm happy to capture logs again.

I'm going to input all the other keybindings now and see if the joystick keeps working. Will let you know

**Comment by tfulmer1** [comment]
False alarm I guess -- Joystick still is not working in the game. I'm unclear if it actually worked the first time, or if the injection wasn't working and the game was detecting the raw input from the game pad.

After the above, I stopped injection and saved the "test" config off as the game name. I then re-enabled and could not move. At first I thought maybe because I had restarted the virtual device, the game wasn't recognizing it anymore. So I restarted the game and still could not move. So I stopped injection, added a new keymap (not the analog joystick) and restarted injection and that key works but joystick still does not. 

On the bright side I'm not hanging anymore with the analog setting, but for some reason still not getting the input through which was the original issue again. I'm clearly your problem child

**Comment by jonasBoss** [comment]
can you check the lutris wine-controlpanel to see which gamepads are recognized.

**Comment by tfulmer1** [comment]
Wine Control Panel detects two forwarded devices:
input-remapper Azeron LTD Azeron Keypad Forwarded  <---- This one does not register joystick movement but registers key presses in the test Joystick mode

input-remapper gamepad  <---- this one registers joystick movement but not key presses in the test Joystick mode

As well as the original Azeron device.

============

This got me wondering if the inputs were getting confused on the game end as you'd mentioned that as a likely problem before I swapped to the beta branch and ruled it out as the original problem.

I MAY have found the problem (not yours) doing that. It looks like the game will (real time) swap to a different interface which goes back to your original suspicion about the game detection.

The game accepts inputs from any keyboard attached, but it will only accept inputs from one gamepad and was still detecting both gamepads. So when I swapped from using keyboard dpad inputs for the joystick and started using gamepad analog, it was not swapping to the new gamepad since it can still detect (and just not receive inputs from) the true device.

If I manually configure the gamepad to point to the emulated one, joystick works. Every time I stop capture it will auto-swap back to the real device it still detects, but that's a game issue I'll have to deal with and not your issue. And once I have all the key maps done, I'll hopefully have no reason to stop capture.

I'm going to (once again) add all the keyboard mappings to the device while not changing the gamepad/joystick settings. Then will give it a go. If everything works I'll let you know and come close the issue.

Hopefully you can track down the unhandled exception above as well from the description

**Comment by tfulmer1** [comment]
I believe it is currently, actually, completely working!

Sorry some of this at the end was user error, but glad I got to test your beta branch and find a few bugs for you in the process.

You've been very helpful/responsive. Thanks!

If I have any further issues I'll let you know

**Comment by jonasBoss** [comment]
Thank you for taking the time and report all those issues.

It is probably best to deactivate the forwarded devices as well as the original one and only leave the `input-remapper gamepad` active in the controlpanel. This way the game only sees one gamepad.

You can also create mappings for the different buttons on the gamepad. 
Note: the dpad on the `input-remapper gamepad` is actually two analog axis `ABS_HAT0X` and `ABS_HAT0Y`

**Comment by tfulmer1** [comment]
Sigh - 

I restarted input-mapper just to make sure all was fixed and it will not load the saved presets.

Some of the key events register as "Unknown" when I record them. When I initially recorded them, they were all working in the game with input-mapper. When I realoaded the appllication, I got these errors during startup:

15:24:44.434337 81155 GUI DEBUG message_broker.py:105: from data_manager.py:110: Signal=preset: PresetData(name='ffxiv', mappings=[(None, <EventCombination (3, 1, 0)>), (None, <EventCombination (3, 0, 0)>), (None, <EventCombination (1, 706, 1)>), (None, <EventCombination (1, 705, 1)>), (None, <EventCombination (1, 712, 1)>), (None, <EventCombination (1, 711, 1)>), (None, <EventCombination (1, 291, 1)>), (None, <EventCombination (1, 290, 1)>), (None, <EventCombination (1, 289, 1)>), (None, <EventCombination (1, 288, 1)>), (None, <EventCombination (1, 296, 1)>), (None, <EventCombination (1, 295, 1)>), (None, <EventCombination (1, 294, 1)>), (None, <EventCombination (1, 293, 1)>), (None, <EventCombination (1, 300, 1)>), (None, <EventCombination (1, 299, 1)>), (None, <EventCombination (1, 298, 1)>), (None, <EventCombination (1, 297, 1)>), (None, <EventCombination (1, 704, 1)>), (None, <EventCombination (1, 303, 1)>), (None, <EventCombination (1, 302, 1)>), (None, <EventCombination (1, 301, 1)>), (None, <EventCombination (1, 710, 1)>), (None, <EventCombination (1, 292, 1)>), (None, <EventCombination (1, 709, 1)>)], autoload=False)
15:24:44.435415 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Joystick-Y as Joystick-Y>
15:24:44.435490 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Joystick-Y as Joystick-Y>
15:24:44.436083 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Joystick-X as Joystick-X>
15:24:44.436154 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Joystick-X as Joystick-X>
15:24:44.436878 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY3 as Button TRIGGER HAPPY3>
15:24:44.437012 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY3 as Button TRIGGER HAPPY3>
15:24:44.437941 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY2 as Button TRIGGER HAPPY2>
15:24:44.438069 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY2 as Button TRIGGER HAPPY2>
15:24:44.438835 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY9 as Button TRIGGER HAPPY9>
15:24:44.438959 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY9 as Button TRIGGER HAPPY9>
15:24:44.439851 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY8 as Button TRIGGER HAPPY8>
15:24:44.439971 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY8 as Button TRIGGER HAPPY8>
15:24:44.440926 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TOP as Button TOP>
15:24:44.441047 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TOP as Button TOP>
15:24:44.441805 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button THUMB2 as Button THUMB2>
15:24:44.441928 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button THUMB2 as Button THUMB2>
15:24:44.442657 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button THUMB as Button THUMB>
15:24:44.442775 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button THUMB as Button THUMB>
15:24:44.443573 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button JOYSTICK as Button JOYSTICK>
15:24:44.443694 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button JOYSTICK as Button JOYSTICK>
15:24:44.444489 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE3 as Button BASE3>
15:24:44.444608 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE3 as Button BASE3>
15:24:44.445331 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE2 as Button BASE2>
15:24:44.445450 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE2 as Button BASE2>
15:24:44.446250 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE as Button BASE>
15:24:44.446372 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE as Button BASE>
15:24:44.447165 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button PINKIE as Button PINKIE>
15:24:44.447285 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button PINKIE as Button PINKIE>
15:24:44.447884 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448128 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448292 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448340 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448340 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for unknown as unknown>
15:24:44.448400 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448443 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448443 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for unknown as unknown>
15:24:44.448554 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448647 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448738 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448829 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448921 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.448989 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.449051 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.449719 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE6 as Button BASE6>
15:24:44.449843 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE6 as Button BASE6>
15:24:44.450734 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE5 as Button BASE5>
15:24:44.450854 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE5 as Button BASE5>
15:24:44.451832 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE4 as Button BASE4>
15:24:44.451955 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE4 as Button BASE4>
15:24:44.453026 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY as Button TRIGGER HAPPY>
15:24:44.453151 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY as Button TRIGGER HAPPY>
15:24:44.454233 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button DEAD as Button DEAD>
15:24:44.454354 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button DEAD as Button DEAD>
15:24:44.454884 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455123 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455283 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455331 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455331 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for unknown as unknown>
15:24:44.455390 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455430 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455430 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for unknown as unknown>
15:24:44.455542 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455634 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455725 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455816 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455906 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.455969 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.456030 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.456080 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.456120 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.456436 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.456674 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.456842 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.456890 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.456890 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for unknown as unknown>
15:24:44.456953 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.456995 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.456995 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for unknown as unknown>
15:24:44.457107 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.457200 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.457291 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.457393 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.457444 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.457484 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.457573 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.457635 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.457696 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.458240 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY7 as Button TRIGGER HAPPY7>
15:24:44.458359 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY7 as Button TRIGGER HAPPY7>
15:24:44.458846 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.459031 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.459839 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TOP2 as Button TOP2>
15:24:44.459959 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TOP2 as Button TOP2>
15:24:44.461020 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY6 as Button TRIGGER HAPPY6>
15:24:44.461138 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY6 as Button TRIGGER HAPPY6>
15:24:44.467631 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.467756 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.467821 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.467883 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.467980 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.468075 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.468126 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.468168 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.468230 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.468292 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.468385 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.468476 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.468526 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.468568 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.468628 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.468690 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.469222 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.469477 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.469519 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.470405 81155 GUI DEBUG message_broker.py:105: from data_manager.py:123: Signal=mapping: {'event_combination': <EventCombination (1, 294, 1)>, 'target_uinput': 'keyboard', 'output_symbol': 'w'}
15:24:44.478578 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.478705 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.478769 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.478830 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.478923 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.479013 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.479074 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.479135 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.479184 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.479225 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.479314 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.479408 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.479458 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.479498 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.479558 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.479619 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.480223 81155 GUI DEBUG components.py:455: Enabling the code editor
15:24:44.480831 81155 GUI DEBUG message_broker.py:105: from data_manager.py:133: Signal=selected_event: InputEvent(1, 294, 1)
15:24:44.481061 81155 GUI DEBUG message_broker.py:105: from data_manager.py:133: Signal=selected_event: InputEvent(1, 294, 1)
15:24:44.481122 81155 GUI DEBUG message_broker.py:105: from controller.py:126: Signal=status_msg: StatusData(ctx_id=5, msg=None, tooltip=None)
15:24:44.481181 81155 GUI DEBUG message_broker.py:105: from controller.py:126: Signal=status_msg: StatusData(ctx_id=5, msg=None, tooltip=None)
15:24:44.481548 81155 GUI DEBUG reader.py:97: Reader received {'type': 'groups', 'message': '["{\\"paths\\": [\\"/dev/input/event260\\", \\"/dev/input/event259\\"], \\"names\\": [\\"input-remapper keyboard\\", \\"input-remapper gamepad\\"], \\"types\\": [\\"gamepad\\", \\"keyboard\\"], \\"key\\": \\"input-remapper gamepad\\"}", "{\\"paths\\": [\\"/dev/input/event23\\", \\"/dev/input/event22\\", \\"/dev/input/event21\\", \\"/dev/input/event20\\"], \\"names\\": [\\"Generic Virtual HID Consumer Control\\", \\"Generic Virtual HID System Control\\", \\"Generic Virtual HID\\", \\"Generic Virtual HID\\"], \\"types\\": [\\"keyboard\\", \\"mouse\\"], \\"key\\": \\"Generic Virtual HID\\"}", "{\\"paths\\": [\\"/dev/input/event19\\", \\"/dev/input/event16\\", \\"/dev/input/event15\\"], \\"names\\": [\\"Corsair CORSAIR SCIMITAR RGB ELITE Gaming Mouse Keyboard\\", \\"Corsair CORSAIR SCIMITAR RGB ELITE Gaming Mouse Consumer Control\\", \\"Corsair CORSAIR SCIMITAR RGB ELITE Gaming Mouse\\"], \\"types\\": [\\"keyboard\\", \\"mouse\\"], \\"key\\": \\"Corsair CORSAIR SCIMITAR RGB ELITE Gaming Mouse\\"}", "{\\"paths\\": [\\"/dev/input/event11\\", \\"/dev/input/event10\\", \\"/dev/input/event9\\", \\"/dev/input/event5\\"], \\"names\\": [\\"HOLDCHIP USB Gaming Keyboard\\", \\"HOLDCHIP USB Gaming Keyboard Consumer Control\\", \\"HOLDCHIP USB Gaming Keyboard System Control\\", \\"HOLDCHIP USB Gaming Keyboard\\"], \\"types\\": [\\"keyboard\\"], \\"key\\": \\"HOLDCHIP USB Gaming Keyboard\\"}", "{\\"paths\\": [\\"/dev/input/event14\\", \\"/dev/input/event13\\", \\"/dev/input/event12\\"], \\"names\\": [\\"Azeron LTD Azeron Keypad\\", \\"Azeron LTD Azeron Keypad\\", \\"Azeron LTD Azeron Keypad\\"], \\"types\\": [\\"gamepad\\", \\"keyboard\\", \\"mouse\\"], \\"key\\": \\"Azeron LTD Azeron Keypad\\"}", "{\\"paths\\": [\\"/dev/input/event8\\", \\"/dev/input/event7\\"], \\"names\\": [\\"Logitech G432 Gaming Headset\\", \\"Logitech G432 Gaming Headset Consumer Control\\"], \\"types\\": [], \\"key\\": \\"Logitech G432 Gaming Headset\\"}", "{\\"paths\\": [\\"/dev/input/event6\\", \\"/dev/input/event3\\", \\"/dev/input/event2\\"], \\"names\\": [\\"Razer Razer Tartarus V2\\", \\"Razer Razer Tartarus V2 Keyboard\\", \\"Razer Razer Tartarus V2\\"], \\"types\\": [\\"keyboard\\", \\"mouse\\"], \\"key\\": \\"Razer Razer Tartarus V2\\"}"]'}
15:24:44.481716 81155 GUI DEBUG message_broker.py:105: from reader.py:204: Signal=groups: GroupsData(groups={'Generic Virtual HID': [<DeviceType.KEYBOARD: 'keyboard'>, <DeviceType.MOUSE: 'mouse'>], 'Corsair CORSAIR SCIMITAR RGB ELITE Gaming Mouse': [<DeviceType.KEYBOARD: 'keyboard'>, <DeviceType.MOUSE: 'mouse'>], 'HOLDCHIP USB Gaming Keyboard': [<DeviceType.KEYBOARD: 'keyboard'>], 'Azeron LTD Azeron Keypad': [<DeviceType.GAMEPAD: 'gamepad'>, <DeviceType.KEYBOARD: 'keyboard'>, <DeviceType.MOUSE: 'mouse'>], 'Logitech G432 Gaming Headset': [], 'Razer Razer Tartarus V2': [<DeviceType.KEYBOARD: 'keyboard'>, <DeviceType.MOUSE: 'mouse'>]})
15:24:44.482111 81155 GUI DEBUG reader.py:178: Sending start msg to helper for "Azeron LTD Azeron Keypad"
15:24:44.482321 81164 GUI-Helper DEBUG helper.py:129: Received command "Azeron LTD Azeron Keypad"
15:24:44.482467 81164 GUI-Helper DEBUG event_reader.py:92: read loop stopped
15:24:44.482507 81164 GUI-Helper INFO event_reader.py:176: read loop for /dev/input/event14 stopped
15:24:44.482549 81164 GUI-Helper DEBUG event_reader.py:92: read loop stopped
15:24:44.482578 81164 GUI-Helper INFO event_reader.py:176: read loop for /dev/input/event13 stopped
15:24:44.482617 81164 GUI-Helper DEBUG event_reader.py:92: read loop stopped
15:24:44.482645 81164 GUI-Helper INFO event_reader.py:176: read loop for /dev/input/event12 stopped
15:24:44.482963 81155 GUI INFO preset.py:157: Loading preset from "/home/lost/.config/input-remapper/beta_1.6.0-beta/presets/Azeron LTD Azeron Keypad/ffxiv.json"
15:24:44.487540 81164 GUI-Helper DEBUG event_reader.py:166: Starting to listen for events from /dev/input/event14, fd 17
15:24:44.487688 81164 GUI-Helper DEBUG event_reader.py:166: Starting to listen for events from /dev/input/event13, fd 18
15:24:44.487771 81164 GUI-Helper DEBUG event_reader.py:166: Starting to listen for events from /dev/input/event12, fd 19
15:24:44.488890 81155 GUI DEBUG components.py:115: adding Generic Virtual HID to device dropdown 
15:24:44.489031 81155 GUI DEBUG components.py:115: adding Corsair CORSAIR SCIMITAR RGB ELITE Gaming Mouse to device dropdown 
15:24:44.489109 81155 GUI DEBUG components.py:115: adding HOLDCHIP USB Gaming Keyboard to device dropdown 
15:24:44.489183 81155 GUI DEBUG components.py:115: adding Azeron LTD Azeron Keypad to device dropdown 
15:24:44.489258 81155 GUI DEBUG components.py:115: adding Logitech G432 Gaming Headset to device dropdown 
15:24:44.489338 81155 GUI DEBUG components.py:115: adding Razer Razer Tartarus V2 to device dropdown 
15:24:44.489422 81155 GUI DEBUG message_broker.py:105: from data_manager.py:100: Signal=group: GroupData(group_key='Azeron LTD Azeron Keypad', presets=('ffxiv',))
15:24:44.489551 81155 GUI DEBUG message_broker.py:105: from data_manager.py:155: Signal=injector_state: InjectorState(state=5)
15:24:44.489636 81155 GUI DEBUG message_broker.py:105: from data_manager.py:110: Signal=preset: PresetData(name='ffxiv', mappings=[(None, <EventCombination (3, 1, 0)>), (None, <EventCombination (3, 0, 0)>), (None, <EventCombination (1, 706, 1)>), (None, <EventCombination (1, 705, 1)>), (None, <EventCombination (1, 712, 1)>), (None, <EventCombination (1, 711, 1)>), (None, <EventCombination (1, 291, 1)>), (None, <EventCombination (1, 290, 1)>), (None, <EventCombination (1, 289, 1)>), (None, <EventCombination (1, 288, 1)>), (None, <EventCombination (1, 296, 1)>), (None, <EventCombination (1, 295, 1)>), (None, <EventCombination (1, 294, 1)>), (None, <EventCombination (1, 293, 1)>), (None, <EventCombination (1, 300, 1)>), (None, <EventCombination (1, 299, 1)>), (None, <EventCombination (1, 298, 1)>), (None, <EventCombination (1, 297, 1)>), (None, <EventCombination (1, 704, 1)>), (None, <EventCombination (1, 303, 1)>), (None, <EventCombination (1, 302, 1)>), (None, <EventCombination (1, 301, 1)>), (None, <EventCombination (1, 710, 1)>), (None, <EventCombination (1, 292, 1)>), (None, <EventCombination (1, 709, 1)>)], autoload=False)
15:24:44.492628 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Joystick-Y as Joystick-Y>
15:24:44.492693 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Joystick-Y as Joystick-Y>
15:24:44.493201 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Joystick-X as Joystick-X>
15:24:44.493262 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Joystick-X as Joystick-X>
15:24:44.493863 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY3 as Button TRIGGER HAPPY3>
15:24:44.493982 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY3 as Button TRIGGER HAPPY3>
15:24:44.494671 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY2 as Button TRIGGER HAPPY2>
15:24:44.494789 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY2 as Button TRIGGER HAPPY2>
15:24:44.495496 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY9 as Button TRIGGER HAPPY9>
15:24:44.495615 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY9 as Button TRIGGER HAPPY9>
15:24:44.496473 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY8 as Button TRIGGER HAPPY8>
15:24:44.496594 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY8 as Button TRIGGER HAPPY8>
15:24:44.497472 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TOP as Button TOP>
15:24:44.497591 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TOP as Button TOP>
15:24:44.498376 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button THUMB2 as Button THUMB2>
15:24:44.498493 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button THUMB2 as Button THUMB2>
15:24:44.499275 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button THUMB as Button THUMB>
15:24:44.499392 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button THUMB as Button THUMB>
15:24:44.500183 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button JOYSTICK as Button JOYSTICK>
15:24:44.500303 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button JOYSTICK as Button JOYSTICK>
15:24:44.501172 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE3 as Button BASE3>
15:24:44.501289 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE3 as Button BASE3>
15:24:44.502214 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE2 as Button BASE2>
15:24:44.502334 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE2 as Button BASE2>
15:24:44.503296 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE as Button BASE>
15:24:44.503519 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE as Button BASE>
15:24:44.504365 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button PINKIE as Button PINKIE>
15:24:44.504513 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button PINKIE as Button PINKIE>
15:24:44.505359 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.505629 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.505802 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.505849 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.505849 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for unknown as unknown>
15:24:44.505909 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.505950 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.505950 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for unknown as unknown>
15:24:44.506060 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.506151 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.506214 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.506275 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.506931 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE6 as Button BASE6>
15:24:44.507053 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE6 as Button BASE6>
15:24:44.508097 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE5 as Button BASE5>
15:24:44.508216 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE5 as Button BASE5>
15:24:44.509369 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button BASE4 as Button BASE4>
15:24:44.509490 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button BASE4 as Button BASE4>
15:24:44.510637 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY as Button TRIGGER HAPPY>
15:24:44.510759 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY as Button TRIGGER HAPPY>
15:24:44.511895 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button DEAD as Button DEAD>
15:24:44.512014 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button DEAD as Button DEAD>
15:24:44.512880 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513125 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513287 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513345 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513345 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for unknown as unknown>
15:24:44.513405 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513445 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513445 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for unknown as unknown>
15:24:44.513556 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513647 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513696 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.513735 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513822 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513883 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.513942 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.514265 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.514504 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.514675 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.514722 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.514722 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for unknown as unknown>
15:24:44.514782 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.514823 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.514823 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for unknown as unknown>
15:24:44.514934 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.515025 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.515077 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.515117 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.515165 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.515205 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.515292 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.515354 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.515415 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.515960 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY7 as Button TRIGGER HAPPY7>
15:24:44.516080 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY7 as Button TRIGGER HAPPY7>
15:24:44.517087 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TOP2 as Button TOP2>
15:24:44.517209 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TOP2 as Button TOP2>
15:24:44.518196 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_mapping_changed of SelectionLabel for Button TRIGGER HAPPY6 as Button TRIGGER HAPPY6>
15:24:44.518316 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method SelectionLabel._on_combination_update of SelectionLabel for Button TRIGGER HAPPY6 as Button TRIGGER HAPPY6>
15:24:44.523801 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.523932 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.524024 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.524106 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.524186 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.524303 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.524431 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.524533 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.524594 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.524641 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.524679 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.524736 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.524854 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.524971 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.525039 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.525092 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.525216 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.525308 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.525392 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.525984 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.526251 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.526293 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.527101 81155 GUI DEBUG message_broker.py:105: from data_manager.py:123: Signal=mapping: {'event_combination': <EventCombination (1, 294, 1)>, 'target_uinput': 'keyboard', 'output_symbol': 'w'}
15:24:44.527920 81155 GUI DEBUG components.py:455: Enabling the code editor
15:24:44.534099 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.534256 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.534392 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.534490 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.534587 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.534724 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.534859 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.534937 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.534999 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.535138 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.535239 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.535332 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.535466 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.535602 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.535682 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 300, 1)
15:24:44.535744 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.535818 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 302, 1)
15:24:44.535879 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.536012 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.536107 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.536172 81155 GUI ERROR input_event.py:218: Unknown code for InputEvent(1, 301, 1)
15:24:44.536352 81155 GUI DEBUG message_broker.py:105: from data_manager.py:133: Signal=selected_event: InputEvent(1, 294, 1)
15:24:44.536420 81155 GUI DEBUG message_broker.py:105: from data_manager.py:133: Signal=selected_event: InputEvent(1, 294, 1)
15:24:44.536472 81155 GUI DEBUG message_broker.py:105: from controller.py:126: Signal=status_msg: StatusData(ctx_id=5, msg=None, tooltip=None)
15:24:44.536518 81155 GUI DEBUG message_broker.py:105: from controller.py:126: Signal=status_msg: StatusData(ctx_id=5, msg=None, tooltip=None)
15:24:49.063484 81155 GUI DEBUG message_broker.py:124: adding new Listener: <bound method Controller.show_injector_result of <inputremapper.gui.controller.Controller object at 0x7f9b4901c6d0>>
15:24:49.063634 81155 GUI DEBUG message_broker.py:105: from controller.py:532: Signal=status_msg: StatusData(ctx_id=1, msg='Starting injection...', tooltip=None)
15:24:49.178001 81155 GUI DEBUG message_broker.py:105: from controller.py:532: Signal=status_msg: StatusData(ctx_id=1, msg='Failed to apply preset ffxiv', tooltip=None)


This may go back to my dpad attempt error? I originally (pre-beta) had mapped the joystick to the dpad and everything worked (just a little squirrely, but all future restarts (after I changed a key mapping) failed to start up even after re-installing. 

I'm thinking maybe the save file isn't handling key inputs it doesn't have a name for?

**Comment by tfulmer1** [comment]
That was longer than I thought, should have just attached another log. But still -- possible save file issue?

**Comment by tfulmer1** [comment]
![image](https://user-images.githubusercontent.com/11013393/180662850-050be541-a87e-493e-af42-9bf5bf87ca5e.png)

**Comment by tfulmer1** [comment]
GUI issue -- Clicking any of those unknowns will sometimes select a different unknown.

**Comment by tfulmer1** [comment]
Sorry, spamming with comments

I deleted the offending buttons, exited the GUI and restarted the gui (log showed it started error free). Still could not start the injection. Did a ps and saw more than one copy of the service was running. I killed the gtk process, all the service processes and the helper process manually. Restarted gtk and loaded the config. It loaded error free and injection started.

So if I boot up in that bad state with the 'Unknown" inputs, it apparently messes with the service and won't recover after a GUI shutdown/restart even if it shows a clean load.

Killing all processes, starting up clean everything seems to be working again (joystick + other keys) except I can't use the 3-4 keys that were "unknown" input names. I could only use them in the same session I recorded them.

I'll stop spamming comments now and give you time to digest. No rush, I can at play the game with a couple of dead keys as I'm still gaining more keys than I had before.

**Comment by jonasBoss** [comment]
those Unknown events are exactly this: Unknown. The names come from the [linux kernel](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h)
and the event codes 300-303 are not defined there.

You can give those mappings a custom name if you press the little pencil next to the name in the mapping list this should allow you distinguish them.

And I will change the auto-generated name to include the event code.

**Comment by jonasBoss** [comment]
I just pushed some changes to my abs_to_abs branch.
You should now get a message in the gui if you miss the "use as analog" switch and the unknown inputs now include the event code. 
The unknown inputs no longer jump around when the list gets re-sorted.

I would appreciate if you can test those fixes.

**Comment by tfulmer1** [comment]
"use as analog" error message:
--I disabled the advanced analog setting on one of the axis, error message appeared

"Unknown Inputs include event code":
--I mapped two unknown keys, they mapped with even code
--Confirmed the buttons worked in the game
--restarted input-remapper
--Lots of errors still about unknown input in the debug log, but injection started and the keys worked

"Unknown Inputs no longer jump around":
--Confirmed

**Comment by jonasBoss** [comment]
closing because fixes got merged into beta
